version: '2'
services:
  #######################################
  # nginx server 
  #######################################
    www:
        image: nginx:latest
        links:
            - php
            - maildev
            - elasticsearch
            - postgres
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/sf4.nginx.conf:/etc/nginx/conf.d/default.conf
            # - ./docker/nginx/sf3.nginx.conf:/etc/nginx/conf.d/default.conf
            - ./www:/var/www/html
            - vendor:/var/www/html/vendor
            - sfcache:/var/www/html/app/cache
            - ./var/nginx:/var/log/nginx
        # cap and privileged needed for slowlog
        cap_add:
            - SYS_PTRACE
        privileged: true
        env_file:
            - etc/environment.yml
            - etc/environment.development.yml

    #######################################
    # maildev mail server
    #######################################
    maildev:
        image: djfarrelly/maildev
        ports:
            - "8081:80"

    #######################################
    # php fpm
    #######################################
    php:
        build:
            context: docker/php/
            dockerfile: Php-7.2.Dockerfile
            # dockerfile: Php-7.1.Dockerfile
            # dockerfile: Php-7.0.Dockerfile
        volumes: 
            - ./www:/var/www/html
            - vendor:/var/www/html/vendor
            - sfcache:/var/www/html/app/cache
            - composer:/var/www/html/.composer
            - ./var/php:/var/log/php
        links:
            - maildev
            - elasticsearch
            - postgres
        env_file:
            - etc/environment.yml
            - etc/environment.development.yml
        environment:
            - COMPOSER_HOME=/var/www/html/.composer


    #######################################
    # Elasticsearch
    #######################################
    elasticsearch:
        build:
            context: docker/elasticsearch/
            dockerfile: Elasticsearch-5.6.6.Dockerfile
        # cap_add:
        #     - IPC_LOCK
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        env_file:
            - etc/environment.yml
            - etc/environment.development.yml

    ############## PostgreSQL #############
    #######################################
    # PostgreSQL server
    #######################################
    postgres:
        build:
            context: docker/postgres/
            # dockerfile: Postgres-9.4.Dockerfile
            dockerfile: Postgres-9.5.Dockerfile
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        # environment:
        #     - LANG=fr_FR.UTF-8
        env_file:
            - etc/environment.yml
            - etc/environment.development.yml

    #######################################
    # phpPgAdmin
    #######################################
    phpPgAdmin:
        container_name: phppgadmin
        image: fizix/docker-pgadmin:php-fpm-environment
        # environment:
        #     - POSTGRESQL_HOST=postgres
        #     - POSTGRESQL_PORT=5432
        #     - POSTGRESQL_DEFAULT_DB=postgres
        ports:
            - 8088:80
        links:
            - postgres
        env_file:
            - etc/environment.yml
            - etc/environment.development.yml

volumes:
    #### composer cache folder
    composer:
    #### vendor folder
    vendor:
    #### symfony var folder
    sfcache:
    #### postgres data folder
    postgres:
    #### elasticsearch data folder
    elasticsearch:
